spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/authorization_role_MM
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: task8.domain
server:
  servlet:
    session:
      tracking-modes: cookie